<h1>Импорт библиотек

In [6]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [7]:
import numpy as np

def sum_prod(X, V):
    '''
    X - матрицы (n, n)
    V - векторы (n, 1)
    Гарантируется, что len(X) == len(V)
    '''
    return np.sum(np.dot(X, V))

X = np.array([[1, 2], [3, 4]])
V = np.array([[5], [6]])
print(sum_prod(X, V))  # 56

X = np.array([[1, 2, 3], [4, 5, 6]])
V = np.array([[1], [2], [3]])
print(sum_prod(X, V))  # 46

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
V = np.array([[1], [1], [1]])
print(sum_prod(X, V))  # 45

X = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
V = np.array([[1], [2], [3]])
print(sum_prod(X, V))  # 6

X = np.array([[1, 2], [3, 4], [5, 6]])
V = np.array([[1], [1]])
print(sum_prod(X, V))  # 21

56
46
45
6
21


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [9]:
import numpy as np

def binarize(M, threshold=0.5):
    return np.where(M > threshold, 1, 0)

M = np.array([[0.2, 0.8], [0.6, 0.4]])
threshold = 0.5
print(binarize(M, threshold))  # [[0 1] [1 0]]

M = np.array([[0.1, 0.9], [0.3, 0.7]])
threshold = 0.3
print(binarize(M, threshold))  # [[0 1] [0 1]]

M = np.array([[0.6, 0.7, 0.8], [0.1, 0.2, 0.3]])
threshold = 0.6
print(binarize(M, threshold))  # [[0 1 1] [0 0 0]]

M = np.array([[0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])
threshold = 0.7
print(binarize(M, threshold))  # [[0 0 0] [1 1 1]]

M = np.array([[0.9, 0.8, 0.7], [0.6, 0.5, 0.4]])
threshold = 0.5
print(binarize(M, threshold))  # [[1 1 1] [1 0 0]]

[[0 1]
 [1 0]]
[[0 1]
 [0 1]]
[[0 1 1]
 [0 0 0]]
[[0 0 0]
 [0 1 1]]
[[1 1 1]
 [1 0 0]]


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [19]:
import numpy as np

def unique_rows(mat):
    arrays = [np.unique(row) for row in mat]
    return arrays

def unique_columns(mat):
    arrays = [np.unique(column) for column in mat.T]
    return arrays

mat = np.array(
    [
    [1, 2, 3], 
    [4, 5, 6], 
    [1, 2, 3]
    ])
print(unique_rows(mat))
print(unique_columns(mat))
print()

mat = np.array(
    [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
    ])
print(unique_rows(mat))
print(unique_columns(mat))
print()

mat = np.array(
    [
    [1, 1, 1], 
    [2, 2, 2], 
    [3, 3, 3]
    ])
print(unique_rows(mat))
print(unique_columns(mat))
print()

mat = np.array(
    [
    [1, 1, 1], 
    [1, 1, 1], 
    [1, 1, 1]
    ])
print(unique_rows(mat))
print(unique_columns(mat))

[array([1, 2, 3]), array([4, 5, 6]), array([1, 2, 3])]
[array([1, 4]), array([2, 5]), array([3, 6])]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 4, 7]), array([2, 5, 8]), array([3, 6, 9])]

[array([1]), array([2]), array([3])]
[array([1, 2, 3]), array([1, 2, 3]), array([1, 2, 3])]

[array([1]), array([1]), array([1])]
[array([1]), array([1]), array([1])]


<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
# Your code goes here

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [26]:
import numpy as np

def chess(m, n, a, b):
    mat = np.zeros((m, n))
    for i in range(int(m)):
        for j in range(int(n)):
            if (i + j) % 2 == 0:
                mat[i, j] = a
            else:
                mat[i, j] = b
    return mat

print(chess(4, 4, 1, 0))
print()
print(chess(5, 4, 1, 2))
print()
print(chess(1, 0, 1, 0))
                

[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]

[[1. 2. 1. 2.]
 [2. 1. 2. 1.]
 [1. 2. 1. 2.]
 [2. 1. 2. 1.]
 [1. 2. 1. 2.]]

[]


<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [1]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Your code goes here
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    # Your code goes here
    pass

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
# Your code goes here

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
# Your code goes here